### ISSUE TITLE
Difference of DOS between the amorphous structure relaxed by vasp and abacus

### ISSUE THREAD

**Issue by MumuMaster2021** [abacusmodeling/abacus-develop#322]
### Describe the Code Quality Issue

We provide four amorphous structures, Ge10_Bi2_Si59_O143, which use vasp and abacus to relax, and then perform dos calculation after convergence. The results show that the dos calculation of the structure after abacus srelax indicates that it is a conductor, and the optimized configuration after vasp is a semiconductor. According to experience, we prefer this amorphous structure to be a semiconductor. May I ask whether the accuracy of abacus' relax configuration is insufficient or whether other reasons lead to the difference between the above two calculation software results in the convergent configuration?

<img width="604" alt="image" src="https://github.com/abacusmodeling/abacus-develop/assets/143064898/75e5d10a-e263-462f-b0f3-938b357c775e">
<img width="629" alt="image" src="https://github.com/abacusmodeling/abacus-develop/assets/143064898/5c50a7b9-98f2-420b-a0f1-53b9e9de7e7b">

### Task list for Issue attackers (only for developers)

- [ ] Identify the specific code file or section with the code quality issue.
- [X] Investigate the issue and determine the root cause.
- [X] Research best practices and potential solutions for the identified issue.
- [ ] Refactor the code to improve code quality, following the suggested solution.
- [ ] Ensure the refactored code adheres to the project's coding standards.
- [ ] Test the refactored code to ensure it functions as expected.
- [ ] Update any relevant documentation, if necessary.
- [ ] Submit a pull request with the refactored code and a description of the changes made.

**Comment by dyzheng** [comment]
Can you upload your ABACUS input files to repeat your results? 

Another question is what is the `E_Fermi` value from ABACUS? 
The zero energy point of output DOS file from ABACUS is not the Fermi energy.

**Comment by MumuMaster2021** [comment]
Hi，daye
This zip includes two structure results calculated by vasp  and abacus.
来自飞书邮箱的超大附件
[image: https://sf1-cdn-tos.douyinstatic.com/obj/eden-cn/fuupceh7nupfnupfnuhog/icon_file_unknow.png]
issue-322.tar.gz
208.7 MB将于 Jun 13, 2024 失效
下载<https://www.feishu.cn/mail/page/attachment?token=R9GgbPIe5oHL1YxckwJczcranac>
> From: ***@***.***>
> Date:  Tue, May 28, 2024, 23:11
> Subject:  Re: [abacusmodeling/abacus-develop] Difference of DOS between the amorphous structure relaxed by vasp and abacus (Issue #322)
> To: ***@***.***>
> Cc: ***@***.***>, ***@***.***>
> Can you upload your ABACUS input files to repeat your results?
> Another question is what is the 
> E_Fermi
>  value from ABACUS?
> 
The zero energy point of output DOS file from ABACUS is not the Fermi energy.

**Comment by MumuMaster2021** [comment]
we use config.json , and execute abacus plot 功能 {
    "pdosfile": "PDOS",
    "efermi": 2.5311038583,
    "energy_range": [
        -5,
        5
    ],
    "dos_range": [
        0,
        10
    ],
    "figsize": [
        14,
        10
    ],
    "species": {
        "Si": [
            0,
            1,
            2
        ],
        "O": [
            0,
            1,
            2
        ],
        "Bi": [
            0,
            1,
            2,
            3
        ]
    },
    "pdosfig": "pdos.png"
}

**Comment by dyzheng** [comment]
@MumuMaster2021 I checked the band energys and occuaptions from VASP, which imply a small bandgap semi-conductor as well as ABACUS. 
I also notice that the `smearing_sigma 0.01` in ABACUS(unit: Ry) is larger than `SIGMA 0.05` in VASP(unit: eV), you can try `smearing_sigma 0.0037` in ABACUS and recalculate this case.

**Comment by mohanchen** [comment]
Thanks for your advice, would you like to propose a new issue on deepmodeling/abacus?(https://github.com/deepmodeling/abacus-develop) We will discuss issues there.
