### ISSUE TITLE
 !! CONVERGENCE HAS NOT BEEN ACHIEVED !!

### ISSUE THREAD

**Issue by duousername1** [abacusmodeling/abacus-develop#329]
### Describe the bug

When running ABACUS with the following input parameters, the program encountered an error during the SCF calculation. The error messages are:

1. "!! CONVERGENCE HAS NOT BEEN ACHIEVED !!"
2. "2024-07-25 17:19:53,475 - INFO: job: b131ef03975b49cc0e0af19b716b0ebefcb0fbc3 13911562:job_group_id:12998244 terminated; fail_count is 1; resubmitting job"
3. "2024-07-25 17:19:53,828 - INFO: job: b131ef03975b49cc0e0af19b716b0ebefcb0fbc3 re-submit after terminated; new job_id is 13947468:job_group_id:12998244"
4. The input files are in the following compressed package.
[init_2.47CeAl2_NH4ClO4_c64_m512.zip](https://github.com/user-attachments/files/16373959/init_2.47CeAl2_NH4ClO4_c64_m512.zip)

### Expected behavior

ABACUS should complete the SCF calculation with errors.谢谢！！

### Task list for Issue attackers (only for developers)

- [X] Verify the issue is not a duplicate.
- [X] Describe the bug.
- [X] Steps to reproduce.
- [X] Expected behavior.
- [X] Error message.
- [X] Environment details.
- [X] Additional context.
- [X] Assign a priority level (low, medium, high, urgent).
- [X] Assign the issue to a team member.
- [X] Label the issue with relevant tags.
- [X] Identify possible related issues.
- [X] Create a unit test or automated test to reproduce the bug (if applicable).
- [X] Fix the bug.
- [X] Test the fix.
- [X] Update documentation (if necessary).
- [X] Close the issue and inform the reporter (if applicable).

**Comment by mohanchen** [comment]
Thanks for your advice, would you like to propose a new issue on deepmodeling/abacus?(https://github.com/deepmodeling/abacus-develop) We will discuss issues there.
